services:
  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    env_file:
      - .env.production
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_SETTINGS_PRODUCTION=True
    depends_on:
      - db
  client:
    build: ./client
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - server
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
volumes:
  postgres_data:
